kind: pipeline
type: docker
name: go-mongodb-migrate

steps:
  - name: linter
    image: golangci/golangci-lint
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOOS: "linux"
      GOARCH: "amd64"
    commands:
      - golangci-lint run -v --timeout 3m

  - name: check-constructs
    image: golang:1.20
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOOS: "linux"
      GOARCH: "amd64"
    commands:
      - make check

  - name: security
    image: golang:1.20
    environment:
      GOOS: "linux"
      GOARCH: "amd64"
    commands:
      - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.14.0
      - gosec ./...

  - name: test
    image: golang:1.20
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOOS: "linux"
      GOARCH: "amd64"
    commands:
      - make test

  - name: build
    image: golang:1.20
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOOS: "linux"
      GOARCH: "amd64"
      GOPRIVATE: "github.com/erodriguezg"
    commands:
      - make install
      - make compile
